language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  slack: constrictproject:ARJgSrhVJqdPp6FdzwFxLVqq
